### ISSUE TITLE
Could not load the character information using Queue System

### ISSUE THREAD

**Issue by rafaeltortella** [vRP-framework/vRP#507]
Hello Guys i need help with a strange error when im using a Queue system and not with the Queue system…

I have trynd  and got the same issue:
https://forum.fivem.net/t/release-c-fivem-queue
https://forum.fivem.net/t/connectqueue-a-server-queue-system

The problem is, when im using this queue system or any other queue system 80% of the player join in the game normally, but the other 20% of the players join in the game but the character information (name, inventory, bank, etc… everything about this player, storage in db mysql) the is not loaded on this player, and the player stay on the server with the default character forever…

If i find this player on my db table like, user_identities and change the license to other user_id and it works, the player login normally but the do not have more the own itens because off course i have changed he user_id... this means for me that with the Queue System for some reason the game can not load something weird on the database from that player and i dont know what to do. 

When i turn off the Queue System all player join in the server and they character information load normally.

Because of this im still need to run my server without Queue =( and this is bad for me… can anyone here please give some information that can help me…

Thanks everyone, have a good day =D,
Infammous.

**Comment by AleDema** [comment]
The issue is caused by the fact most queue scripts require the player to have steam open in order to join the server, otherwise they get kicked. Thing is vRP inserts the player ID into the users table when the same event used by the queue is triggered, that means vRP thinks that user is always in the server, even tho he's not and the issue persists until you restart everything. I'd suggest you to move some of the stuff handled by "playerConnecting" to another event which is triggered when the player is actually spawned, so that if he leaves the server "playerDropped" can be triggered and clean the users table.

**Comment by ImagicTheCat** [comment]
Check if https://github.com/ImagicTheCat/vRP/commit/c8f15381c5839887daecf0e9543c62e95c13a7b2 fixes/improve the issue.
